# Generated by Django 5.2 on 2025-04-28 06:47

import demo_test.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discounts",
            field=models.ManyToManyField(blank=True, to="shop.discount"),
        ),
        migrations.AlterField(
            model_name="premiumproduct",
            name="markup_percentage",
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name="tiereddiscount",
            name="tiers",
            field=models.JSONField(
                default=demo_test.shop.models.TieredDiscount.default_tiers
            ),
        ),
    ]
