# Generated by Django 5.2 on 2025-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_discounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
